import type { Lesson } from "./types";

type PlannedLesson = Pick<Lesson, "id" | "number" | "title" | "emoji" | "stage" | "knowledgePoints">;

function createPlannedLesson(lesson: PlannedLesson): Lesson {
  return {
    ...lesson,
    contentReady: false,
    goal: `本课将学习：${lesson.knowledgePoints}。`,
    taskTitle: "课程内容准备中",
    task: "本课教案、教学视频和代码练习尚未发布。",
    taskSteps: [],
    homework: "",
    hints: [],
    starterCode: "",
  };
}

export const plannedLessons: Lesson[] = [
  createPlannedLesson({
    id: "variable-assignment",
    number: 3,
    title: "装礼物的魔法小盒子",
    emoji: "🎁",
    stage: "变量（概念与赋值）",
    knowledgePoints: "变量的赋值",
  }),
  createPlannedLesson({
    id: "variable-naming",
    number: 4,
    title: "给盒子贴标签，换新礼物",
    emoji: "🏷️",
    stage: "变量（命名与覆盖）",
    knowledgePoints: "变量的命名 · 变量的重新赋值",
  }),
  createPlannedLesson({
    id: "math",
    number: 5,
    title: "超级计算器，一秒出答案",
    emoji: "🧮",
    stage: "数学运算",
    knowledgePoints: "四则运算",
  }),
  createPlannedLesson({
    id: "string-concatenation",
    number: 6,
    title: "文字积木，拼出新花样",
    emoji: "🧱",
    stage: "字符串拼接",
    knowledgePoints: "字符串拼接",
  }),
  createPlannedLesson({
    id: "input",
    number: 7,
    title: "电脑问，我来答",
    emoji: "🎤",
    stage: "输入指令 input()",
    knowledgePoints: "input()",
  }),
  createPlannedLesson({
    id: "type-conversion",
    number: 8,
    title: "文字和数字的变身魔法",
    emoji: "✨",
    stage: "类型转换",
    knowledgePoints: "int() · str()",
  }),
  createPlannedLesson({
    id: "if-comparison",
    number: 9,
    title: "谁大谁小？电脑来判！",
    emoji: "⚖️",
    stage: "if 入门与比较运算符 > <",
    knowledgePoints: "if 语法 · 比较运算符 > <",
  }),
  createPlannedLesson({
    id: "if-else",
    number: 10,
    title: "岔路口，二选一",
    emoji: "🚦",
    stage: "if / else 与比较运算符 ==",
    knowledgePoints: "if / else 语法 · 比较运算符 == !=",
  }),
  createPlannedLesson({
    id: "and-or",
    number: 11,
    title: "两个都要，还是一个就行？",
    emoji: "🎢",
    stage: "多条件判断（and / or）",
    knowledgePoints: "and · or",
  }),
  createPlannedLesson({
    id: "elif",
    number: 12,
    title: "多条岔路，选一条走",
    emoji: "🛤️",
    stage: "多分支判断（elif）",
    knowledgePoints: "elif",
  }),
  createPlannedLesson({
    id: "for-range",
    number: 13,
    title: "让电脑当复读机",
    emoji: "🔁",
    stage: "for 循环（计数循环）",
    knowledgePoints: "for i in range()",
  }),
  createPlannedLesson({
    id: "list-create",
    number: 14,
    title: "玩具排队上火车",
    emoji: "🚂",
    stage: "列表（概念与创建）",
    knowledgePoints: "列表创建",
  }),
  createPlannedLesson({
    id: "list-index",
    number: 15,
    title: "从 0 号车厢开始找",
    emoji: "🔎",
    stage: "列表（索引取值）",
    knowledgePoints: "列表索引",
  }),
  createPlannedLesson({
    id: "list-loop",
    number: 16,
    title: "玩具轮流登场表演",
    emoji: "🎭",
    stage: "for 循环（遍历列表）",
    knowledgePoints: "for item in 列表",
  }),
  createPlannedLesson({
    id: "list-change",
    number: 17,
    title: "车尾添一节，再拆一节",
    emoji: "🧸",
    stage: "列表（增删元素）",
    knowledgePoints: "append() · pop()",
  }),
  createPlannedLesson({
    id: "while-counter",
    number: 18,
    title: "只要有力气，就继续走",
    emoji: "🚶",
    stage: "while 循环（条件循环）",
    knowledgePoints: "while · 计数器自增（i = i + 1）",
  }),
  createPlannedLesson({
    id: "while-break",
    number: 19,
    title: "听到“停”，立刻刹车！",
    emoji: "🛑",
    stage: "while 循环（退出机制）",
    knowledgePoints: "break",
  }),
  createPlannedLesson({
    id: "function-parameters",
    number: 20,
    title: "写菜谱，按订单做菜",
    emoji: "👩‍🍳",
    stage: "函数（定义与调用-带参数）",
    knowledgePoints: "函数定义 · 函数调用",
  }),
  createPlannedLesson({
    id: "function-return",
    number: 21,
    title: "菜做好了，端出来",
    emoji: "🍲",
    stage: "函数（返回值 return）",
    knowledgePoints: "函数返回",
  }),
];
